# Generated by Django 4.1.3 on 2022-11-26 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0002_tags_alter_ingredient_unit_remove_recipe_tags_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
    ]
